Coverage gates added

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -88,4 +88,25 @@ jobs:
       id: deployment
       uses: actions/deploy-pages@v4
 
+    - name: Archive Reports
+      if: always()
+      uses: actions/upload-artifact@v3
+      with:
+        name: coverage-report
+        path: |
+          ${{github.workspace}}/.coverage
 
+    - name: Report to DTP
+      working-directory: ${{github.workspace}}
+      shell: bash
+      run: cpptestcov report dtp -verbose -coverage LC,MCDC -settings dtp.settings test_detail.xml .coverage
+
+    - name: Check Line Quality Gate
+      working-directory: ${{github.workspace}}
+      shell: bash
+      run: COV_VALUE=$(cpptestcov query -coverage LC .coverage) && if [[ $COV_VALUE -lt $LINE_COV_GATE ]]; then echo "Line coverage quality get failed. Expected: $LINE_COV_GATE achieved: $COV_VALUE. Check details here: https://mirek-parasoft.github.io/iceoryx/coverage.html"; exit 1; else echo "Line coverage quality gate passed. Achived: $COV_VALUE is above the gate of $LINE_COV_GATE"; fi
+
+    - name: Check MCDC Quality Gate
+      working-directory: ${{github.workspace}}
+      shell: bash
+      run: COV_VALUE=$(cpptestcov query -coverage MCDC .coverage) && if [[ $COV_VALUE -lt $MCDC_COV_GATE ]]; then echo "MCDC coverage quality get failed. Expected: $MCDC_COV_GATE achieved: $COV_VALUE. Check details here: https://mirek-parasoft.github.io/iceoryx/coverage.html"; exit 1; else echo "MCDC coverage quality gate passed. Achived: $COV_VALUE is above the gate of $MCDC_COV_GATE"; fi
